const AppTopics = [
  {
    id: 1,
    name: "Learn",
    slug: "learn",
    image: "https://picsum.photos/200/300",
    color: "#f5f5f5",
    path: "/learn",
    children: [
      {
        id: 1,
        name: "Books",
        slug: "books",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/learn/books",
      },
      {
        id: 2,
        name: "Tutorials",
        slug: "tutorials",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/learn/tutorials",
        children: [
          {
            id: 1,
            name: "Cooking",
            slug: "cooking",
            image: "https://picsum.photos/200/300",
            color: "#f5f5f5",
            path: "/learn/tutorials/cooking",
          },
          {
            id: 2,
            name: "Sewing",
            slug: "sewing",
            image: "https://picsum.photos/200/300",
            color: "#f5f5f5",
            path: "/learn/tutorials/sewing",
          },
          {
            id: 3,
            name: "Div",
            slug: "div",
            image: "https://picsum.photos/200/300",
            color: "#f5f5f5",
            path: "/learn/tutorials/div",
          },
          {
            id: 4,
            name: "Religion",
            slug: "religion",
            image: "https://picsum.photos/200/300",
            color: "#f5f5f5",
            path: "/learn/tutorials/religion",
            children: [
              {
                id: 1,
                name: "The Holly Qur'an",
                slug: "quran",
                image: "https://picsum.photos/200/300",
                color: "#f5f5f5",
                path: "/learn/tutorials/religion/quran",
              },
              {
                id: 2,
                name: "Stories of the Prophets",
                slug: "stories",
                image: "https://picsum.photos/200/300",
                color: "#f5f5f5",
                path: "/learn/tutorials/religion/stories",
              },
              {
                id: 3,
                name: "Qur'an explanation",
                slug: "explanation",
                image: "https://picsum.photos/200/300",
                color: "#f5f5f5",
                path: "/learn/tutorials/religion/explanation",
              },
              {
                id: 4,
                name: "Islamic advice",
                slug: "advice",
                image: "https://picsum.photos/200/300",
                color: "#f5f5f5",
                path: "/learn/tutorials/religion/advice",
              },
            ],
          },
        ],
      },
      {
        id: 3,
        name: "Languages",
        slug: "languages",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/learn/languages",
      },
      {
        id: 4,
        name: "MOOCs",
        slug: "moocs",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/learn/moocs",
      },
    ],
  },
  {
    id: 2,
    name: "Chat",
    slug: "chat",
    image: "https://picsum.photos/200/300",
    color: "#f5f5f5",
    path: "/chat",
    children: [
      {
        id: 1,
        name: "Chat with users",
        slug: "users",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/chat/users",
      },
      {
        id: 2,
        name: "Digital assistant",
        slug: "assistant",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/chat/assistant",
      },
    ],
  },
  {
    id: 3,
    name: "Entertain",
    slug: "entertain",
    image: "https://picsum.photos/200/300",
    color: "#f5f5f5",
    path: "/entertain",
    children: [
      {
        id: 1,
        name: "Muvies",
        slug: "movies",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/movies",
      },
      {
        id: 2,
        name: "Board games",
        slug: "boardgames",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/boardgames",
      },
      {
        id: 3,
        name: "Movies",
        slug: "movies",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/movies",
      },
      {
        id: 4,
        name: "meditating",
        slug: "meditating",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/meditating",
      },
      {
        id: 5,
        name: "exercising",
        slug: "exercising",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/exercising",
      },
      {
        id: 6,
        name: "radio",
        slug: "radio",
        image: "https://picsum.photos/200/300",
        color: "#f5f5f5",
        path: "/entertain/radio",
      },
    ],
  },
  {
    id: 4,
    name: "Connect",
    slug: "connect",
    image: "https://picsum.photos/200/300",
    color: "#f5f5f5",
    path: "/connect",
  },
  {
    id: 5,
    name: "FeedBack and complaints",
    slug: "feedback",
    image: "https://picsum.photos/200/300",
    color: "#f5f5f5",
    path: "/feedback",
  },
];

export { AppTopics };
